In [25]:
import numpy as np
import torch
import tensorflow as tf

## 8. Norms and Unit Vectors
- L2 norm (euclidean distance): most common
- L1 norm: used whenever difference between zero and non-zero is key
- Squared L2 norm: cheaper than L2 norm, because:
  + is equal to XTX
- Max norm

### $L^2$ Norm

In [3]:
a = np.array([1 ,2 ,3 ])

In [4]:
l2_norm_a = np.sqrt(np.sum(a ** 2))

a_torch = torch.tensor(a)
norm_a = np.linalg.norm(a)
norm_a_torch = np.linalg.norm(a_torch)

print(l2_norm_a)
print(norm_a)
print(norm_a_torch)

3.7416573867739413
3.7416573867739413
3.7416573867739413


### $L^1$ Norm

In [5]:
l1_norm_a = np.sum(np.abs(a))
l1_norm_a

6

### Squared $L^2$ Norm

In [6]:
sqrt_l2_norm_a = np.sum(a ** 2)
sqrt_l2_norm_a

14

### Max Norm

In [7]:
max_norm_a = np.max(np.abs(a))
max_norm_a

3

## 9. Basic, Orthogonal, Orthonormal vectors

### Basic vectors

### Orthonormal vectors

In [8]:
i = np.array([0, 1])
j = np.array([1, 0])
np.dot(i,j)

0

### Orthonormal vectors

In [9]:
i.T @ j

0

## 10. Vector

In [22]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
A_torch = torch.tensor([[1,2,3],[4,5,6]])
A_torch

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
A_tf = tf.Variable([[1,2,3],[4,5,6]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [23]:
# First col
print(A[:,0])
# Second row
print(A[1,:])
# Get all rows, col from 1 to 2 (not included)
print(A[:,1:2])
# Element at second col, third row
print(A[1][2])

[1 4]
[4 5 6]
[[2]
 [5]]
6


In [24]:
# First col
print(A_torch[:,0])
# Second row
print(A_torch[1,:])
# Get all rows, col from 1 to 2 (not included)
print(A_torch[:,1:2])
# Element at second col, third row
print(A_torch[1][2])

tensor([1, 4])
tensor([4, 5, 6])
tensor([[2],
        [5]])
tensor(6)


In [27]:
# First col
print(A_tf[:,0])
# Second row
print(A_tf[1,:])
# Get all rows, col from 1 to 2 (not included)
print(A_tf[:,1:2])
# Element at second col, third row
print(A_tf[1][2])

tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [31]:
tf.rank(A_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## 11. Generic tensor notation

In [ ]:
# High-rank tensors
A = np.zeros((32,28,28,3))
A 

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

## 12. Excercises

In [ ]:
# 1. Transpose of a vector
A = np.array([[25],[5],[-3],[-23]])
print(A)
print(f"Transpose of vector A: {A.T}")

[[ 25]
 [  5]
 [ -3]
 [-23]]
Transpose of vector A: [[ 25   5  -3 -23]]


In [ ]:
# 2. dimension of matrix Y =>  2x4
Y = np.array([[92, 4, 7, 99],[-99,-3,17,22]])
print(Y.shape)

(2, 4)


In [39]:
# 3. Positio of "17" => 2,3, or [1][2]
result = Y[1][2]
print(result)

17
