# Segment 3: Matrix Properties

## 24. Frobenius norm

In [12]:
import numpy as np
import torch

In [13]:
X = np.array([[1,2],[3,4]])
frobenius_norm = np.linalg.norm(X) # or L2 norm
frobenius_norm

5.477225575051661

In [14]:
X_pt = torch.tensor([[1.,2.],[3.,4.]])
print(torch.linalg.norm(X_pt))

tensor(5.4772)


## 25. Matrix Multiplication 

In [15]:
X = np.array([[1,2],[3,4],[5,6]]) # 3x2
Y = np.array([[3,2, 2],[2,1,4]]) # 2x3
# XY = X@Y # 3x3
print(X@Y)
print(np.matmul(X,Y))

[[ 7  4 10]
 [17 10 22]
 [27 16 34]]
[[ 7  4 10]
 [17 10 22]
 [27 16 34]]


In [16]:
X_pt = torch.from_numpy(X) # 3x2
X_pt
Y_pt = torch.tensor([[3,2, 2],[2,1,4]],dtype=torch.int32) # 2x3
print(X_pt@Y_pt)
print(torch.matmul(X_pt,Y_pt))

tensor([[ 7,  4, 10],
        [17, 10, 22],
        [27, 16, 34]], dtype=torch.int32)
tensor([[ 7,  4, 10],
        [17, 10, 22],
        [27, 16, 34]], dtype=torch.int32)


## 26. Symmetric and Identity Matrices
- Symmetric matrix: Square, $X^T = X$
- Indentity matrix ($I_n$): every element along main diagonal is 1, other elements are 0
  + n-length vector unchanged if multiplied by $I_n$

In [17]:
X_sym = np.array([[0,1,2],[1,7,8],[2,8,9]])
print(X_sym.T == X_sym)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
# Identity matrix
I = torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
x_pt = torch.tensor([3,6,7])
print(I.matmul(x_pt))
print(x_pt.matmul(I))

tensor([3, 6, 7])
tensor([3, 6, 7])


## 27. Matrix Multiplication Excercises

In [19]:
A = torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
B = torch.tensor([-1,1,-2])
C = torch.tensor([[-1,0],[1,1],[-2,2]])
# My result: A.B = [-3, -9, -15]
# My result: A.C = [[-3, -9, -15], [5, 14, 23]]
print(A.matmul(B))
print(torch.matmul(A,B))
print(torch.matmul(A,C))

tensor([ -3,  -9, -15])
tensor([ -3,  -9, -15])
tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])


## 28. Matrix Inversion
- $ X^{-1} . X = I_n$
y = Xw
- Assuming $X^{-1}$ exists, matrix inversion can solve for w:
  + w = $X^{-1}y$
- Singular matrix: square, does not have an inverse, determinant = 0

In [20]:
X = torch.tensor([[4.,2.],[-5.,-3.]])
y = torch.tensor([4.,-7.])
w = torch.matmul(torch.inverse(X), y)
w

tensor([-1.,  4.])

In [21]:
# Singular matrix
X = np.array([[-4,1],[-8,2]])
X_inv = np.linalg.inv(X)

LinAlgError: Singular matrix

## 29. Diagonal Matrices
- Identity matrix is a special type of diagonal matrices
- If square: diag(x), x is vector of main-diagonal elements

In [ ]:
X = np.array([[3,0,0],[0,2,0],[0,0,9]])
X

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 9]])

## 30. Orthogonal Matrices
- $A^TA = AA^T = I $
- $ A^T = A^{-1}I = A^{-1}$

In [ ]:
# Orthogonal vectors
i = np.array([1,0])
j = np.array([0,1])
print(i.dot(j))

0


## 31. Orthogonal Matrix Excercises
- Identity matrices are orthogonal

In [ ]:
I3 = np.array([[1,0,0],[0,1,0],[0,0,1]])

# Dot product of columns
dot_col_1_2 = I3[:,0].dot(I3[:,1])
dot_col_1_3 = I3[:,0].dot(I3[:,2])
dot_col_2_3 = I3[:,1].dot(I3[:,2])
print(dot_col_1_2,dot_col_1_3,dot_col_1_3)

# Norms of columns
print(np.linalg.norm(I3[:,0]))
print(np.linalg.norm(I3[:,1]))
print(np.linalg.norm(I3[:,2]))

# 
is_orthogonal = np.allclose(I3.T @ I3, np.eye(I3.shape[0]))
is_orthogonal

0 0 0
1.0
1.0
1.0


True

In [23]:
K = np.array([[2/3,1/3,2/3],[-2/3,2/3,1/3],[1/3,2/3,-2/3]])

# Dot products of columns
print(K[:,0].dot(K[:,1]))
print(K[:,0].dot(K[:,2]))
print(K[:,1].dot(K[:,2]))

# Norms of columns
print(np.linalg.norm(K[:,0]))
print(np.linalg.norm(K[:,1]))
print(np.linalg.norm(K[:,2]))

# 
is_orthogonal = np.allclose(K.T @ K, np.eye(K.shape[0]))
print("Is K orthogonal: ",is_orthogonal)

0.0
0.0
0.0
1.0
1.0
1.0
Is K orthogonal:  True


$ Q^{-1} = Q^T$

In [ ]:
print(np.allclose(np.linalg.inv(K), np.transpose(K)))

True
