# Segment 2: Tensor operation

## 15. Tensor tranposition

In [2]:
import numpy as np
import torch as torch
import tensorflow as tf

In [9]:
X = np.array([[25,2],[5,26],[3,7]])
X_torch = torch.tensor([[25,2],[5,26],[3,7]])
X_tf = tf.Variable([[25,2],[5,26],[3,7]])
print(X)
print(X.T)
print(X_torch.T)
print(tf.transpose(X_tf))

[[25  2]
 [ 5 26]
 [ 3  7]]
[[25  5  3]
 [ 2 26  7]]
tensor([[25,  5,  3],
        [ 2, 26,  7]])
tf.Tensor(
[[25  5  3]
 [ 2 26  7]], shape=(2, 3), dtype=int32)


## 16. Basic tensor arithmetic. The Hadamard Product
The Hadamard Product: the element-wise product ($A \odot B$)

In [16]:
# Add, multiply with a scalar
print(X * 2 + 2)
print(np.add(np.multiply(X,2),2))
print(X_torch * 2 + 2)
print(torch.add(torch.mul(X_torch,2),2))
print(tf.add(tf.multiply(X_tf,2),2))

[[52  6]
 [12 54]
 [ 8 16]]
[[52  6]
 [12 54]
 [ 8 16]]
tensor([[52,  6],
        [12, 54],
        [ 8, 16]])
tensor([[52,  6],
        [12, 54],
        [ 8, 16]])
tf.Tensor(
[[52  6]
 [12 54]
 [ 8 16]], shape=(3, 2), dtype=int32)


In [18]:
A = X + 1
A

array([[26,  3],
       [ 6, 27],
       [ 4,  8]])

In [20]:
print(A+X)
print(A-X)
print(A * X)
print(A/X)

[[51  5]
 [11 53]
 [ 7 15]]
[[1 1]
 [1 1]
 [1 1]]
[[650   6]
 [ 30 702]
 [ 12  56]]
[[1.04       1.5       ]
 [1.2        1.03846154]
 [1.33333333 1.14285714]]


## 17. Tensor reduction

In [23]:
X.sum()
print(torch.sum(X_torch))
print(tf.reduce_sum(X_tf))

tensor(68)
tf.Tensor(68, shape=(), dtype=int32)


In [24]:
X.max()

26

## 18. Dot product
- $x \cdot y$
- $x^Ty$
- $\langle x, y \rangle$

In [25]:
x = np.array([25, 2, 5])
y = np.array([0, 1, 2])

In [28]:
print(np.dot(x,y))
print(x @ y)
print(torch.dot(torch.tensor(x),torch.tensor(y)))
# print(tf.dot)

12
12
tensor(12, dtype=torch.int32)


In [37]:
x_tf = tf.Variable(x)
y_tf = tf.Variable(y)
print(tf.reduce_sum(tf.multiply(x_tf, y_tf)))
print(tf.reduce_sum(x_tf * y_tf))
print(tf.tensordot(x_tf,y_tf,axes=1))

tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


## 19. Excercises on Tensor operations

In [ ]:
# 1.
y = np.array([[42, 4, 7, 99],[-99, -3, 17, 22]])
# My result: yT(2x4) = [[42 -99], [4, -3], [7, 18], [99, 22]]
y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [40]:
# 2. Hadamard product
a = np.array([[25,10],[-2, 1]])
b = np.array([[-1,7],[10,8]])
# My result: (2x2) [[-25, 70], [-20, 8]]
a * b

array([[-25,  70],
       [-20,   8]])

In [41]:
# 3. Dot product of the tensors w and x
w = np.array([-1, 2, -2])
x = np.array([5, 10, 0])
# My result: 15
w @ x

15